#! /bin/bash

rm -f myhttpd.log
../myhttpd 0 > /dev/null 2>&1 &
PID=$!

prlimit --nproc=50 --cpu=600 --rss=4000000 -p $PID

sleep 1
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)
diff -wq <(curl -s -u $USERSTRING "127.0.0.1:$PORT") ./http-root-dir/htdocs/index.html
CODE=$?
if [[ $CODE != 0 ]]; then
  printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
  exit 1
else
  diff -w ./myhttpd.log <(curl -s -u $USERSTRING "127.0.0.1:$PORT/logs")
  if [[ $? != 0 ]]; then
    printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
    kill -15 $PID
    exit 0
  else
    printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
    kill -15 $PID
    exit 1
  fi
fi
