#! /bin/bash

../myhttpsd 0 > /dev/null 2>&1 &
PID=$!

prlimit --nproc=200 --cpu=600 --rss=4000000 -p $PID

sleep 1
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat auth.txt)
curl -k -s -u $USERSTRING --cert-status "https://127.0.0.1:$PORT/simple.html"
diff -qw <(curl -k -s -u $USERSTRING "https://127.0.0.1:$PORT/simple.html") ./http-root-dir/htdocs/simple.html
CODE=$?
kill -15 $PID
if [[ $CODE != 0 ]]; then
  printf "$(basename "$0") Failed.\n"
  exit 0
else
  printf "$(basename "$0") Passed.\n"
  exit 1
fi
