#! /bin/bash

../myhttpd 0 > /dev/null 2>&1 &
PID=$!

prlimit --nproc=50 --cpu=600 --rss=4000000 -p $PID

sleep 1
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)
CODE=$(curl -s -i -u $USERSTRING "127.0.0.1:$PORT" | head -n 1 | awk '{print $2}' | grep "200")
RES=$?
kill -15 $PID
if [[ $RES != 0 ]]; then
  printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
  exit 0
else
  printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
  exit 1
fi
