#! /bin/bash

../myhttpsd 0 &
PID=$!
sleep 1
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)
mkdir -p tmp
curl -L -s -k -u $USERSTRING "https://127.0.0.1:$PORT/directory/" | grep -i -E "href" | grep -v -E "C=N|C=M|C=S" | grep -v -i "parent" | LC_COLLATE=C sort > ./tmp/test-iterative-directory-listing-slash-tls
diff -y <(LC_COLLATE="C" ls -p1 ./http-root-dir/htdocs/directory/) <(python3 htmlsearch.py ./tmp/test-iterative-directory-listing-slash-tls)
if [[ $? != 0 ]]; then
    printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
    rm -rf ./tmp
    kill -15 $PID
    exit 0
fi
printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
rm -rf ./tmp
kill -15 $PID
exit 1
