#! /bin/bash
function abort() {
    printf "\033[0;31m$(basename "$0") Failed.\033[0m\n"
    rm -rf ./tmp
    kill -15 $PID
    exit 0
}

../myhttpd 0 > /dev/null 2>&1 &
PID=$!
sleep 1
PORT=$(netstat -ntlp 2> /dev/null | awk 'split($7, a, "/"); split($4, b, ":"); {print b[2]" "a[1]}' | awk -v pid="$PID" '$2==pid {print $1}')
USERSTRING=$(cat ../auth.txt)

# Randomize last modified times
for FILE in ./http-root-dir/htdocs/directory/*; do
  touch -m -t $(date -d @$(shuf -i "0-$(date +%s)" -n 1) +%Y%m%d%H%M.%S) "$FILE"
done

mkdir -p tmp
./rowsearch.py 1 $PORT "/directory/" > ./tmp/test-iterative-directory-properties

for f in ./http-root-dir/htdocs/directory/*; do
    # echo "f: ${f}"
    d=$(date -r "$f" --u "+%a %b%3e %H:%M:%S %Y")
    s=$(stat --printf="%s" "$f")
    f=${f##*/}
    # echo "d: ${d}"
    # echo "s: ${s}"
    grep "${f}" ./tmp/test-iterative-directory-properties | grep -q "${d}"
    if [[ $? != 0 ]]; then
        echo date ${d} not found for $f
        cat ./tmp/test-iterative-directory-properties
        abort
    fi
    grep "${f}" ./tmp/test-iterative-directory-properties | grep -q "${s}"
    if [[ $? != 0 ]]; then
        echo size ${s} not found for $f
        cat ./tmp/test-iterative-directory-properties
        abort
    fi
done
printf "\033[0;32m$(basename "$0") Passed.\033[0m\n"
rm -rf ./tmp
kill -15 $PID
exit 1
