#!/bin/bash

(make clean; make) || exit 1

source ../../tester/testall

runtest mytest "test1" none 1 6
runtest mytest "test2" none 1 6
runtest mytest "test3" none 1 3
runtest mytest "test4" none 1 3
runtest mytest "test5" none 1 3

printResults
gitadd "*.h *.c" 

